version: '3'

services:
  postgresql-master:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=w2ERWdQfKnQ2haaadnTjy7mLELYFKufh
      - POSTGRES_DATABASE=gomani
    networks:
      - api_network_local

  mongodb-master:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGODB_USERNAME=mongodb
      - MONGODB_PASSWORD=59zp6xCfTsHbjUh99mw4fvKU6VGNCaVN
      - MONGODB_DATABASE=gomani
    networks:
      - api_network_local

  redis-master:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=
      - ALLOW_EMPY_PASSWORD=yes
    networks:
      - api_network_local

volumes:
  postgresql_master_data:
    driver: local

networks:
  api_network_local:
